version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    image: api-gen-proto
    container_name: api-gen-proto
    restart: "no"
    volumes:
      - ./proto:/app/proto
      - ./gen/go:/app/tmp/gitlab.bcasia.io/thuynga/apps/api/gen/go
      - ./gen/ts:/app/gen/ts
    command: bash -c "make order && cd tmp/gitlab.bcasia.io/thuynga/apps/api/gen/go && ls -la"